---
title: "Exploratory Data Analysis"
output: 
  rmdformats::material:
    code_folding: hide
css: custom.css
---
# Preface

...tbd :)

```{r, include=F}
knitr::opts_chunk$set(
  echo = F,
  warning = F,
  collapse = T,
  comment = F,
  out.width = "100%",
  dpi = 300,
  message = F,
  dev = "svglite",
  fig.ext = ".svg"
)
options(scipen = 999)

library(rvest)
library(tidyverse)
library(svglite)
library(ggplot2)
library(extrafont)
library(ggtext)
#font_import()
loadfonts(device = "win")
windowsFonts()

```
```{r}

theme_set(theme_minimal())
theme_update(
    panel.grid.minor = element_line(size = 0.25),
    panel.grid.major = element_line(size = 0.75),
    plot.title = element_text(face = "bold", size = 22),
    plot.subtitle = element_text(size = 16),
    text = element_text(color = "#111d2b", family = "Segoe UI", size = 18),
    panel.background = element_rect(fill = '#ffffff', color = '#ffffff'),
    plot.background = element_rect(fill = '#ffffff', color = '#ffffff'),
    axis.text.x = element_text(angle = 90),
    axis.title = element_text(face = "bold", size = 15),
    axis.title.y = element_text(vjust = +2),
    axis.title.x = element_text(vjust = -0.75)
)

```

# Polish Footbal
```{r}

url <- "https://pl.wikipedia.org/wiki/Reprezentacja_Polski_w_pi%C5%82ce_no%C5%BCnej_m%C4%99%C5%BCczyzn"
dfList <- 
  read_html(url) %>%
  html_nodes(., '.wikitable') %>%
  html_table(., fill = TRUE)

dfFifaPosition <- which(sapply(dfList, ncol) == 13)
dfFifa <- dfList[[dfFifaPosition]]

dfTeamPosition <- which(sapply(dfList, nrow) >= 38 & sapply(dfList, ncol) == 6)
dfTeam <- dfList[[dfTeamPosition]]
```

```{r}
dfFifa %>%
  rename("year" = 1) %>%
  mutate(across(everything(), ~as.character(.x))) %>%
  pivot_longer(
    cols = 2:13,
    names_to = "month",
    values_to = "position"
  ) %>%
  mutate(position = as.numeric(position)) -> dfFifa
```

```{r, echo = T}
s <- svgstring(width = 12, height = 6)

 dfFifa %>%
  ggplot(aes(
    x = year,
    y = position
  )) +
  geom_boxplot()
 
htmltools::HTML(s())
invisible(dev.off())
```

```{r, echo = T}
s <- svgstring(width = 12, height = 6)

dfFifa %>%
  group_by(year) %>%
  mutate(mean = mean(position, na.rm = T)) %>%
  ggplot(aes(
    x = as.numeric(year),
    y = mean
  )) +
  geom_line(color = "#F93943", size = 1.7) + 
  ### WORST
  annotate(
    "text",
    x = 2003.5,
    y = 68, 
    label = "The worst place in \n FIFA ranking \n (2013, 78th)",
    color = "#111d2b",
    fontface = 'bold',
    size = 5
  ) +
  geom_point(aes(y = position), color = "#111d2b", size = 2, alpha = .5) +
  scale_x_continuous(breaks = seq(1990, max(dfFifa$year), na.rm = T, 2)) +
  scale_y_continuous( breaks = seq(0, 80, 5)) +
  annotate(
    'curve',
    x = 2006.5,
    y = 72,
    yend = 78,
    xend = 2012.5,
    linewidth = 1,
    curvature = -0.2,
    arrow = arrow(length = unit(0.5, 'cm')),
    color = "#111d2b"
  ) +
  ### PEAK
  annotate(
    "text",
    x = 2012,
    y = 16, 
    label = "Poland's peak in \n FIFA ranking \n (2017, 5th)",
    color = "#111d2b",
    fontface = 'bold',
    size = 5
  ) +
  geom_point(aes(y = position), color = "#111d2b", size = 2, alpha = .5) +
  scale_x_continuous(breaks = seq(1990, max(dfFifa$year), na.rm = T, 2)) +
  scale_y_continuous( breaks = seq(0, 80, 5)) +
  annotate(
    'curve',
    x = 2014,
    y = 11.5,
    yend = 6.5,
    xend = 2016.5,
    linewidth = 1,
    curvature = -0.35,
    arrow = arrow(length = unit(0.5, 'cm')),
    color = "#111d2b"
  ) +
  labs(
    x = "Ranked year",
    y = "Position (the higher the worse)",
    title = "How is polish footbal team performing in the FIFA ranking?",
    subtitle = "year's average with each month's rank marked",
    caption = "Author: MK \n data source: wikipedia \n men's national football team"
  )

htmltools::HTML(s())
invisible(dev.off())
```

```{r}
dfTeam <- 
  dfTeam %>%
  rename(
    "id" = 1,
    "player" = 2,
    "years" = 3,
    "goals" = 4,
    "matches" = 5
  ) %>%
  mutate(
    debut = as.numeric(gsub("–.*", "", years)),
    off = as.numeric(gsub(".*–", "", years)),
    off = if_else(is.na(off), year(Sys.Date()), off)
  )

```

```{r}
s <- svgstring(width = 12, height = 6)

dfTeam %>%
  ggplot(aes(
    x = goals
  )) +
  geom_histogram(binwidth = 5, aes(y = ..density..)) + 
  geom_density(color = "red", size = 1.6) 

htmltools::HTML(s())
invisible(dev.off())
```


```{r, echo = T}
s <- svgstring(width = 12, height = 9)

dfTeam %>%
  arrange(-debut) %>%
  mutate(
    id = row_number(),
    goals_buket = cut(goals, breaks = c(0, 20, 45, 1000), labels = c("[0, 20]", "[20, 45]", "45+"))
  ) %>%
  ggplot() + 
  geom_rect(aes(
    xmin = debut,
    xmax = off,
    ymin = id + .4,
    ymax = id - .4,
    fill = goals_buket
  ), show.legend = F) +
  geom_text(aes(
    x = debut - 1.5,
    y = if_else(id < 35, id, NA),
    label = paste0(player, " (", goals, ")")
  ), hjust = 1) + 
  geom_text(aes(
    x = off + 1.5,
    y = if_else(id >= 35, id, NA),
    label = paste0(player, " (", goals, ")")
  ), hjust = 0) + 
  scale_x_continuous(breaks = seq(min(dfTeam$debut, na.rm = T) - 2, max(dfTeam$off, na.rm = T), 4)) +
  theme(
    axis.line.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    plot.subtitle = element_markdown()
  ) + 
  scale_fill_manual(
    values = c(
      "#111d2b",
      "#2f4f77",
      "#d1000a"
    )
  ) +
  labs(
    x = "Year played (from debut to off)",
    y = "",
    title = "The best stikers in the history of polish football",
    subtitle = glue::glue(
      "
      divided into 3 caegories:
      <span style = 'color: #111d2b;'> [10, 20] </span>,
      <span style = 'color: #2f4f77;'> [20, 45] </span>,
      <span style = 'color: #d1000a;'> 46+ </span>
      "
    )
  )


htmltools::HTML(s())
invisible(dev.off())
```

